// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ImBinary.proto
// Protobuf Java Version: 4.28.2

package cn.ether.im.proto.binary;

public final class ImBinary {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_cn_ether_im_proto_binary_ImBinaryProto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 2,
                /* suffix= */ "",
                ImBinary.class.getName());
    }

    static {
        java.lang.String[] descriptorData = {
                "\n\016ImBinary.proto\022\030cn.ether.im.proto.bina" +
                        "ry\"[\n\rImBinaryProto\022\014\n\004type\030\001 \001(\005\022<\n\004bod" +
                        "y\030\002 \001(\0132..cn.ether.im.proto.binary.ImMes" +
                        "sageBinaryProto\"\227\002\n\024ImMessageBinaryProto" +
                        "\022\021\n\tmessageId\030\001 \001(\003\022\025\n\010senderId\030\002 \001(\tH\000\210" +
                        "\001\001\022\033\n\016senderTerminal\030\003 \001(\005H\001\210\001\001\022\030\n\013messa" +
                        "geType\030\004 \001(\005H\002\210\001\001\022\024\n\007content\030\005 \001(\tH\003\210\001\001\022" +
                        "\030\n\013contentType\030\006 \001(\005H\004\210\001\001\022\025\n\010sendTime\030\007 " +
                        "\001(\003H\005\210\001\001B\013\n\t_senderIdB\021\n\017_senderTerminal" +
                        "B\016\n\014_messageTypeB\n\n\010_contentB\016\n\014_content" +
                        "TypeB\013\n\t_sendTimeb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_ether_im_proto_binary_ImBinaryProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor,
                new java.lang.String[]{"Type", "Body",});
        internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor,
                new java.lang.String[]{"MessageId", "SenderId", "SenderTerminal", "MessageType", "Content", "ContentType", "SendTime",});
        descriptor.resolveAllFeaturesImmutable();
    }

    private ImBinary() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface ImBinaryProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.ether.im.proto.binary.ImBinaryProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 type = 1;</code>
         *
         * @return The type.
         */
        int getType();

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         *
         * @return Whether the body field is set.
         */
        boolean hasBody();

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         *
         * @return The body.
         */
        cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getBody();

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         */
        cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder getBodyOrBuilder();
    }

    public interface ImMessageBinaryProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.ether.im.proto.binary.ImMessageBinaryProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 messageId = 1;</code>
         *
         * @return The messageId.
         */
        long getMessageId();

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return Whether the senderId field is set.
         */
        boolean hasSenderId();

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return The senderId.
         */
        java.lang.String getSenderId();

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return The bytes for senderId.
         */
        com.google.protobuf.ByteString
        getSenderIdBytes();

        /**
         * <code>optional int32 senderTerminal = 3;</code>
         *
         * @return Whether the senderTerminal field is set.
         */
        boolean hasSenderTerminal();

        /**
         * <code>optional int32 senderTerminal = 3;</code>
         *
         * @return The senderTerminal.
         */
        int getSenderTerminal();

        /**
         * <code>optional int32 messageType = 4;</code>
         *
         * @return Whether the messageType field is set.
         */
        boolean hasMessageType();

        /**
         * <code>optional int32 messageType = 4;</code>
         *
         * @return The messageType.
         */
        int getMessageType();

        /**
         * <code>optional string content = 5;</code>
         *
         * @return Whether the content field is set.
         */
        boolean hasContent();

        /**
         * <code>optional string content = 5;</code>
         *
         * @return The content.
         */
        java.lang.String getContent();

        /**
         * <code>optional string content = 5;</code>
         *
         * @return The bytes for content.
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <code>optional int32 contentType = 6;</code>
         *
         * @return Whether the contentType field is set.
         */
        boolean hasContentType();

        /**
         * <code>optional int32 contentType = 6;</code>
         *
         * @return The contentType.
         */
        int getContentType();

        /**
         * <code>optional int64 sendTime = 7;</code>
         *
         * @return Whether the sendTime field is set.
         */
        boolean hasSendTime();

        /**
         * <code>optional int64 sendTime = 7;</code>
         *
         * @return The sendTime.
         */
        long getSendTime();
    }

    /**
     * Protobuf type {@code cn.ether.im.proto.binary.ImBinaryProto}
     */
    public static final class ImBinaryProto extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:cn.ether.im.proto.binary.ImBinaryProto)
            ImBinaryProtoOrBuilder {
        public static final int TYPE_FIELD_NUMBER = 1;
        public static final int BODY_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:cn.ether.im.proto.binary.ImBinaryProto)
        private static final cn.ether.im.proto.binary.ImBinary.ImBinaryProto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<ImBinaryProto>
                PARSER = new com.google.protobuf.AbstractParser<ImBinaryProto>() {
            @java.lang.Override
            public ImBinaryProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    ImBinaryProto.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new cn.ether.im.proto.binary.ImBinary.ImBinaryProto();
        }

        private int bitField0_;
        private int type_ = 0;
        private cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto body_;
        private byte memoizedIsInitialized = -1;
        // Use ImBinaryProto.newBuilder() to construct.
        private ImBinaryProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private ImBinaryProto() {
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor;
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.ether.im.proto.binary.ImBinary.ImBinaryProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImBinaryProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ImBinaryProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImBinaryProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.ether.im.proto.binary.ImBinary.ImBinaryProto.class, cn.ether.im.proto.binary.ImBinary.ImBinaryProto.Builder.class);
        }

        /**
         * <code>int32 type = 1;</code>
         *
         * @return The type.
         */
        @java.lang.Override
        public int getType() {
            return type_;
        }

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         *
         * @return Whether the body field is set.
         */
        @java.lang.Override
        public boolean hasBody() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         *
         * @return The body.
         */
        @java.lang.Override
        public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getBody() {
            return body_ == null ? cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance() : body_;
        }

        /**
         * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
         */
        @java.lang.Override
        public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder getBodyOrBuilder() {
            return body_ == null ? cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance() : body_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != 0) {
                output.writeInt32(1, type_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(2, getBody());
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, type_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getBody());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.ether.im.proto.binary.ImBinary.ImBinaryProto)) {
                return super.equals(obj);
            }
            cn.ether.im.proto.binary.ImBinary.ImBinaryProto other = (cn.ether.im.proto.binary.ImBinary.ImBinaryProto) obj;

            if (getType()
                    != other.getType()) return false;
            if (hasBody() != other.hasBody()) return false;
            if (hasBody()) {
                if (!getBody()
                        .equals(other.getBody())) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            if (hasBody()) {
                hash = (37 * hash) + BODY_FIELD_NUMBER;
                hash = (53 * hash) + getBody().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ImBinaryProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.ether.im.proto.binary.ImBinary.ImBinaryProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code cn.ether.im.proto.binary.ImBinaryProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.ether.im.proto.binary.ImBinaryProto)
                cn.ether.im.proto.binary.ImBinary.ImBinaryProtoOrBuilder {
            private int bitField0_;
            private int type_;
            private cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto body_;
            private com.google.protobuf.SingleFieldBuilder<
                    cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder> bodyBuilder_;

            // Construct using cn.ether.im.proto.binary.ImBinary.ImBinaryProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImBinaryProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.ether.im.proto.binary.ImBinary.ImBinaryProto.class, cn.ether.im.proto.binary.ImBinary.ImBinaryProto.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage
                        .alwaysUseFieldBuilders) {
                    getBodyFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                type_ = 0;
                body_ = null;
                if (bodyBuilder_ != null) {
                    bodyBuilder_.dispose();
                    bodyBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImBinaryProto_descriptor;
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImBinaryProto getDefaultInstanceForType() {
                return cn.ether.im.proto.binary.ImBinary.ImBinaryProto.getDefaultInstance();
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImBinaryProto build() {
                cn.ether.im.proto.binary.ImBinary.ImBinaryProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImBinaryProto buildPartial() {
                cn.ether.im.proto.binary.ImBinary.ImBinaryProto result = new cn.ether.im.proto.binary.ImBinary.ImBinaryProto(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(cn.ether.im.proto.binary.ImBinary.ImBinaryProto result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.type_ = type_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.body_ = bodyBuilder_ == null
                            ? body_
                            : bodyBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.ether.im.proto.binary.ImBinary.ImBinaryProto) {
                    return mergeFrom((cn.ether.im.proto.binary.ImBinary.ImBinaryProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.ether.im.proto.binary.ImBinary.ImBinaryProto other) {
                if (other == cn.ether.im.proto.binary.ImBinary.ImBinaryProto.getDefaultInstance()) return this;
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (other.hasBody()) {
                    mergeBody(other.getBody());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                type_ = input.readInt32();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                input.readMessage(
                                        getBodyFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>int32 type = 1;</code>
             *
             * @return The type.
             */
            @java.lang.Override
            public int getType() {
                return type_;
            }

            /**
             * <code>int32 type = 1;</code>
             *
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(int value) {

                type_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int32 type = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             *
             * @return Whether the body field is set.
             */
            public boolean hasBody() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             *
             * @return The body.
             */
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getBody() {
                if (bodyBuilder_ == null) {
                    return body_ == null ? cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance() : body_;
                } else {
                    return bodyBuilder_.getMessage();
                }
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public Builder setBody(cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto value) {
                if (bodyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    body_ = value;
                } else {
                    bodyBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public Builder setBody(
                    cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder builderForValue) {
                if (bodyBuilder_ == null) {
                    body_ = builderForValue.build();
                } else {
                    bodyBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public Builder mergeBody(cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto value) {
                if (bodyBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) != 0) &&
                            body_ != null &&
                            body_ != cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance()) {
                        getBodyBuilder().mergeFrom(value);
                    } else {
                        body_ = value;
                    }
                } else {
                    bodyBuilder_.mergeFrom(value);
                }
                if (body_ != null) {
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000002);
                body_ = null;
                if (bodyBuilder_ != null) {
                    bodyBuilder_.dispose();
                    bodyBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder getBodyBuilder() {
                bitField0_ |= 0x00000002;
                onChanged();
                return getBodyFieldBuilder().getBuilder();
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder getBodyOrBuilder() {
                if (bodyBuilder_ != null) {
                    return bodyBuilder_.getMessageOrBuilder();
                } else {
                    return body_ == null ?
                            cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance() : body_;
                }
            }

            /**
             * <code>.cn.ether.im.proto.binary.ImMessageBinaryProto body = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<
                    cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder>
            getBodyFieldBuilder() {
                if (bodyBuilder_ == null) {
                    bodyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                            cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder>(
                            getBody(),
                            getParentForChildren(),
                            isClean());
                    body_ = null;
                }
                return bodyBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:cn.ether.im.proto.binary.ImBinaryProto)
        }

    }

    /**
     * Protobuf type {@code cn.ether.im.proto.binary.ImMessageBinaryProto}
     */
    public static final class ImMessageBinaryProto extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:cn.ether.im.proto.binary.ImMessageBinaryProto)
            ImMessageBinaryProtoOrBuilder {
        public static final int MESSAGEID_FIELD_NUMBER = 1;
        public static final int SENDERID_FIELD_NUMBER = 2;
        public static final int SENDERTERMINAL_FIELD_NUMBER = 3;
        public static final int MESSAGETYPE_FIELD_NUMBER = 4;
        public static final int CONTENT_FIELD_NUMBER = 5;
        public static final int CONTENTTYPE_FIELD_NUMBER = 6;
        public static final int SENDTIME_FIELD_NUMBER = 7;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:cn.ether.im.proto.binary.ImMessageBinaryProto)
        private static final cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<ImMessageBinaryProto>
                PARSER = new com.google.protobuf.AbstractParser<ImMessageBinaryProto>() {
            @java.lang.Override
            public ImMessageBinaryProto parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    ImMessageBinaryProto.class.getName());
        }

        static {
            DEFAULT_INSTANCE = new cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto();
        }

        private int bitField0_;
        private long messageId_ = 0L;
        @SuppressWarnings("serial")
        private volatile java.lang.Object senderId_ = "";
        private int senderTerminal_ = 0;
        private int messageType_ = 0;
        @SuppressWarnings("serial")
        private volatile java.lang.Object content_ = "";
        private int contentType_ = 0;
        private long sendTime_ = 0L;
        private byte memoizedIsInitialized = -1;

        // Use ImMessageBinaryProto.newBuilder() to construct.
        private ImMessageBinaryProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private ImMessageBinaryProto() {
            senderId_ = "";
            content_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor;
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ImMessageBinaryProto> parser() {
            return PARSER;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.class, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder.class);
        }

        /**
         * <code>int64 messageId = 1;</code>
         *
         * @return The messageId.
         */
        @java.lang.Override
        public long getMessageId() {
            return messageId_;
        }

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return Whether the senderId field is set.
         */
        @java.lang.Override
        public boolean hasSenderId() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return The senderId.
         */
        @java.lang.Override
        public java.lang.String getSenderId() {
            java.lang.Object ref = senderId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                senderId_ = s;
                return s;
            }
        }

        /**
         * <code>optional string senderId = 2;</code>
         *
         * @return The bytes for senderId.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getSenderIdBytes() {
            java.lang.Object ref = senderId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                senderId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int32 senderTerminal = 3;</code>
         *
         * @return Whether the senderTerminal field is set.
         */
        @java.lang.Override
        public boolean hasSenderTerminal() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional int32 senderTerminal = 3;</code>
         *
         * @return The senderTerminal.
         */
        @java.lang.Override
        public int getSenderTerminal() {
            return senderTerminal_;
        }

        /**
         * <code>optional int32 messageType = 4;</code>
         *
         * @return Whether the messageType field is set.
         */
        @java.lang.Override
        public boolean hasMessageType() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional int32 messageType = 4;</code>
         *
         * @return The messageType.
         */
        @java.lang.Override
        public int getMessageType() {
            return messageType_;
        }

        /**
         * <code>optional string content = 5;</code>
         *
         * @return Whether the content field is set.
         */
        @java.lang.Override
        public boolean hasContent() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>optional string content = 5;</code>
         *
         * @return The content.
         */
        @java.lang.Override
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>optional string content = 5;</code>
         *
         * @return The bytes for content.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int32 contentType = 6;</code>
         *
         * @return Whether the contentType field is set.
         */
        @java.lang.Override
        public boolean hasContentType() {
            return ((bitField0_ & 0x00000010) != 0);
        }

        /**
         * <code>optional int32 contentType = 6;</code>
         *
         * @return The contentType.
         */
        @java.lang.Override
        public int getContentType() {
            return contentType_;
        }

        /**
         * <code>optional int64 sendTime = 7;</code>
         *
         * @return Whether the sendTime field is set.
         */
        @java.lang.Override
        public boolean hasSendTime() {
            return ((bitField0_ & 0x00000020) != 0);
        }

        /**
         * <code>optional int64 sendTime = 7;</code>
         *
         * @return The sendTime.
         */
        @java.lang.Override
        public long getSendTime() {
            return sendTime_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (messageId_ != 0L) {
                output.writeInt64(1, messageId_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, senderId_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeInt32(3, senderTerminal_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeInt32(4, messageType_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 5, content_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                output.writeInt32(6, contentType_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                output.writeInt64(7, sendTime_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (messageId_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, messageId_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, senderId_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, senderTerminal_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, messageType_);
            }
            if (((bitField0_ & 0x00000008) != 0)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(5, content_);
            }
            if (((bitField0_ & 0x00000010) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(6, contentType_);
            }
            if (((bitField0_ & 0x00000020) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(7, sendTime_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto)) {
                return super.equals(obj);
            }
            cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto other = (cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto) obj;

            if (getMessageId()
                    != other.getMessageId()) return false;
            if (hasSenderId() != other.hasSenderId()) return false;
            if (hasSenderId()) {
                if (!getSenderId()
                        .equals(other.getSenderId())) return false;
            }
            if (hasSenderTerminal() != other.hasSenderTerminal()) return false;
            if (hasSenderTerminal()) {
                if (getSenderTerminal()
                        != other.getSenderTerminal()) return false;
            }
            if (hasMessageType() != other.hasMessageType()) return false;
            if (hasMessageType()) {
                if (getMessageType()
                        != other.getMessageType()) return false;
            }
            if (hasContent() != other.hasContent()) return false;
            if (hasContent()) {
                if (!getContent()
                        .equals(other.getContent())) return false;
            }
            if (hasContentType() != other.hasContentType()) return false;
            if (hasContentType()) {
                if (getContentType()
                        != other.getContentType()) return false;
            }
            if (hasSendTime() != other.hasSendTime()) return false;
            if (hasSendTime()) {
                if (getSendTime()
                        != other.getSendTime()) return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getMessageId());
            if (hasSenderId()) {
                hash = (37 * hash) + SENDERID_FIELD_NUMBER;
                hash = (53 * hash) + getSenderId().hashCode();
            }
            if (hasSenderTerminal()) {
                hash = (37 * hash) + SENDERTERMINAL_FIELD_NUMBER;
                hash = (53 * hash) + getSenderTerminal();
            }
            if (hasMessageType()) {
                hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
                hash = (53 * hash) + getMessageType();
            }
            if (hasContent()) {
                hash = (37 * hash) + CONTENT_FIELD_NUMBER;
                hash = (53 * hash) + getContent().hashCode();
            }
            if (hasContentType()) {
                hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
                hash = (53 * hash) + getContentType();
            }
            if (hasSendTime()) {
                hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                        getSendTime());
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ImMessageBinaryProto> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code cn.ether.im.proto.binary.ImMessageBinaryProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.ether.im.proto.binary.ImMessageBinaryProto)
                cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProtoOrBuilder {
            private int bitField0_;
            private long messageId_;
            private java.lang.Object senderId_ = "";
            private int senderTerminal_;
            private int messageType_;
            private java.lang.Object content_ = "";
            private int contentType_;
            private long sendTime_;

            // Construct using cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.class, cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.Builder.class);
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                messageId_ = 0L;
                senderId_ = "";
                senderTerminal_ = 0;
                messageType_ = 0;
                content_ = "";
                contentType_ = 0;
                sendTime_ = 0L;
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return cn.ether.im.proto.binary.ImBinary.internal_static_cn_ether_im_proto_binary_ImMessageBinaryProto_descriptor;
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto getDefaultInstanceForType() {
                return cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance();
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto build() {
                cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto buildPartial() {
                cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto result = new cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.messageId_ = messageId_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.senderId_ = senderId_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.senderTerminal_ = senderTerminal_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.messageType_ = messageType_;
                    to_bitField0_ |= 0x00000004;
                }
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.content_ = content_;
                    to_bitField0_ |= 0x00000008;
                }
                if (((from_bitField0_ & 0x00000020) != 0)) {
                    result.contentType_ = contentType_;
                    to_bitField0_ |= 0x00000010;
                }
                if (((from_bitField0_ & 0x00000040) != 0)) {
                    result.sendTime_ = sendTime_;
                    to_bitField0_ |= 0x00000020;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto) {
                    return mergeFrom((cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto other) {
                if (other == cn.ether.im.proto.binary.ImBinary.ImMessageBinaryProto.getDefaultInstance()) return this;
                if (other.getMessageId() != 0L) {
                    setMessageId(other.getMessageId());
                }
                if (other.hasSenderId()) {
                    senderId_ = other.senderId_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (other.hasSenderTerminal()) {
                    setSenderTerminal(other.getSenderTerminal());
                }
                if (other.hasMessageType()) {
                    setMessageType(other.getMessageType());
                }
                if (other.hasContent()) {
                    content_ = other.content_;
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                if (other.hasContentType()) {
                    setContentType(other.getContentType());
                }
                if (other.hasSendTime()) {
                    setSendTime(other.getSendTime());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 8: {
                                messageId_ = input.readInt64();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 8
                            case 18: {
                                senderId_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 24: {
                                senderTerminal_ = input.readInt32();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 24
                            case 32: {
                                messageType_ = input.readInt32();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 32
                            case 42: {
                                content_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            case 48: {
                                contentType_ = input.readInt32();
                                bitField0_ |= 0x00000020;
                                break;
                            } // case 48
                            case 56: {
                                sendTime_ = input.readInt64();
                                bitField0_ |= 0x00000040;
                                break;
                            } // case 56
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            /**
             * <code>int64 messageId = 1;</code>
             *
             * @return The messageId.
             */
            @java.lang.Override
            public long getMessageId() {
                return messageId_;
            }

            /**
             * <code>int64 messageId = 1;</code>
             *
             * @param value The messageId to set.
             * @return This builder for chaining.
             */
            public Builder setMessageId(long value) {

                messageId_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>int64 messageId = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessageId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                messageId_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @return Whether the senderId field is set.
             */
            public boolean hasSenderId() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @return The senderId.
             */
            public java.lang.String getSenderId() {
                java.lang.Object ref = senderId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    senderId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @param value The senderId to set.
             * @return This builder for chaining.
             */
            public Builder setSenderId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                senderId_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @return The bytes for senderId.
             */
            public com.google.protobuf.ByteString
            getSenderIdBytes() {
                java.lang.Object ref = senderId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    senderId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @param value The bytes for senderId to set.
             * @return This builder for chaining.
             */
            public Builder setSenderIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                senderId_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>optional string senderId = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSenderId() {
                senderId_ = getDefaultInstance().getSenderId();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 senderTerminal = 3;</code>
             *
             * @return Whether the senderTerminal field is set.
             */
            @java.lang.Override
            public boolean hasSenderTerminal() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional int32 senderTerminal = 3;</code>
             *
             * @return The senderTerminal.
             */
            @java.lang.Override
            public int getSenderTerminal() {
                return senderTerminal_;
            }

            /**
             * <code>optional int32 senderTerminal = 3;</code>
             *
             * @param value The senderTerminal to set.
             * @return This builder for chaining.
             */
            public Builder setSenderTerminal(int value) {

                senderTerminal_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 senderTerminal = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSenderTerminal() {
                bitField0_ = (bitField0_ & ~0x00000004);
                senderTerminal_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 messageType = 4;</code>
             *
             * @return Whether the messageType field is set.
             */
            @java.lang.Override
            public boolean hasMessageType() {
                return ((bitField0_ & 0x00000008) != 0);
            }

            /**
             * <code>optional int32 messageType = 4;</code>
             *
             * @return The messageType.
             */
            @java.lang.Override
            public int getMessageType() {
                return messageType_;
            }

            /**
             * <code>optional int32 messageType = 4;</code>
             *
             * @param value The messageType to set.
             * @return This builder for chaining.
             */
            public Builder setMessageType(int value) {

                messageType_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 messageType = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessageType() {
                bitField0_ = (bitField0_ & ~0x00000008);
                messageType_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @return Whether the content field is set.
             */
            public boolean hasContent() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @return The content.
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @param value The content to set.
             * @return This builder for chaining.
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                content_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @return The bytes for content.
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @param value The bytes for content to set.
             * @return This builder for chaining.
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                content_ = value;
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>optional string content = 5;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContent() {
                content_ = getDefaultInstance().getContent();
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 contentType = 6;</code>
             *
             * @return Whether the contentType field is set.
             */
            @java.lang.Override
            public boolean hasContentType() {
                return ((bitField0_ & 0x00000020) != 0);
            }

            /**
             * <code>optional int32 contentType = 6;</code>
             *
             * @return The contentType.
             */
            @java.lang.Override
            public int getContentType() {
                return contentType_;
            }

            /**
             * <code>optional int32 contentType = 6;</code>
             *
             * @param value The contentType to set.
             * @return This builder for chaining.
             */
            public Builder setContentType(int value) {

                contentType_ = value;
                bitField0_ |= 0x00000020;
                onChanged();
                return this;
            }

            /**
             * <code>optional int32 contentType = 6;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearContentType() {
                bitField0_ = (bitField0_ & ~0x00000020);
                contentType_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 sendTime = 7;</code>
             *
             * @return Whether the sendTime field is set.
             */
            @java.lang.Override
            public boolean hasSendTime() {
                return ((bitField0_ & 0x00000040) != 0);
            }

            /**
             * <code>optional int64 sendTime = 7;</code>
             *
             * @return The sendTime.
             */
            @java.lang.Override
            public long getSendTime() {
                return sendTime_;
            }

            /**
             * <code>optional int64 sendTime = 7;</code>
             *
             * @param value The sendTime to set.
             * @return This builder for chaining.
             */
            public Builder setSendTime(long value) {

                sendTime_ = value;
                bitField0_ |= 0x00000040;
                onChanged();
                return this;
            }

            /**
             * <code>optional int64 sendTime = 7;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSendTime() {
                bitField0_ = (bitField0_ & ~0x00000040);
                sendTime_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:cn.ether.im.proto.binary.ImMessageBinaryProto)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
