spring:
  application:
    name: ether-im-message
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        username: nacos
        password: nacos