spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db-ether-im?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      auto-commit: true
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      connection-timeout: 5000
      minimum-idle: 10
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: 10
        # 连接池最大空闲连接数(使用负值表示没有限制)
        max-idle: 8
        min-idle: 4
        max-wait: 5000
    address: redis://localhost:6379

rocketmq:
  name-server: localhost:9876
  producer:
    group: im-message-group-producer
    #    重试次数，加上第一次，共4次
    retry-times-when-send-failed: 3


redis:
  arrange:
    type: single # single or cluster

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"