spring:
  application:
    name: ether-im-message-group
  profiles:
    active: dev

server:
  port: 8083
  servlet:
    context-path: /im-message-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true