server:
  port: 8899
  id: 1

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        username: nacos
        password: nacos
        namespace: 292fa4e1-6904-48c2-acc8-ab2dae7a1d9e
  redis:
    database: 0
    host: 192.168.1.4
    port: 6379
    password: redis
    timeout: 3000
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000
    address: redis://192.168.1.4:6379

websocket:
  enable: true
  port: 8878
  name: ether-im-ws


rocketmq:
  name-server: 192.168.1.4:9876
  producer:
    group: im-push-producer
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3
    send-message-timeout: 3000
    compress-message-body-threshold: 4096

local:
  cache:
    type: guava

distribute:
  cache:
    type: redis
  lock:
    type: redisson

redis:
  arrange:
    type: single # single or cluster
