spring:
  application:
    name: ether-im-message-single
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        username: nacos
        password: nacos

server:
  servlet:
    context-path: /im-message-single

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true