spring:
  sleuth:
    enabled: true
  application:
    name: ether-im-message-single
  profiles:
    active: dev

server:
  servlet:
    context-path: /im-message-single

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true