spring:
  application:
    name: ether-im-gateway
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务
          enabled: true
      routes:
        - id: im-push
          uri: ws://ether-im-ws
          predicates:
            - Path=/im/**
        # 服务的ID，唯一即可一般与微服务的service name一致
        - id: im-message
          # lb表示负载均衡
          uri: lb://ether-im-message
          predicates:
            - Path=/im-message/**
        - id: im-message-single
          uri: lb://ether-im-message-single
          predicates:
            - Path=/im-message-single/**
  profiles:
    active: dev
server:
  port: 8888