spring:
  application:
    name: ether-im-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务
          enabled: true
      routes:
        - id: im-push
          uri: ws://ether-im-ws
          predicates:
            - Path=/im/**
        - id: im-message-single
          uri: lb://ether-im-message-single
          predicates:
            - Path=/im-message-single/**
        - id: im-message-group
          uri: lb://ether-im-message-group
          predicates:
            - Path=/im-message-group/**
  profiles:
    active: dev
server:
  port: 8888