spring:
  application:
    name: ether-im-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        username: nacos
        password: nacos
        namespace: 292fa4e1-6904-48c2-acc8-ab2dae7a1d9e
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务
          enabled: true
      routes:
        - id: im-push
          uri: ws://ether-im-ws
          predicates:
            - Path=/im/**
        # 服务的ID，唯一即可一般与微服务的service name一致
        - id: im-message
          # lb表示负载均衡
          uri: lb://ether-im-message
          predicates:
            # 路径匹配,所有order的请求都转发到cloud-order-service
            - Path=/im-message/**
        - id: im-message-single
          uri: lb://ether-im-message-single
          predicates:
            - Path=/im-message-single/**
server:
  port: 8888