spring:
  application:
    name: ether-im-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.4:8848
        username: nacos
        password: nacos
        namespace: 292fa4e1-6904-48c2-acc8-ab2dae7a1d9e
server:
  port: 8888